<?php

if ( !defined( 'ABSPATH' ) ) {
    exit;
}

$roles = [
    'manager_postachaniia_vp' => 'Менеджер з постачання',
    'office_admin_vp' => 'Офіс адміністратор',
    'ing_comp_sys_vp' => 'Інженер компютерних систем',
    'designer_graf_vp' => 'Дизайнер графіки',
    'manager_zbutu_vp' => 'Менеджер із збуту',
    'marketolog_vp' => 'Маркетолог',
    'manager_zbutu_vd' => 'Менеджер із збуту',
    'ing_comp_sys_vd' => 'Інженер компютерних систем',
    'bukhhalter_vd' => 'Бухгалтер',
    'region_manager_zbutu_vd' => 'Регіональний менеджер із збуту',
    'manager_zbutu_of' => 'Менеджер із збуту',
    'economist_of' => 'Економіст',
    'nachalnic_viddilu_of' => 'Начальник відділу',
    'zav_po_hosp_tv' => 'Завідуючий по господарчій частині',
    'el_mont_rozpod_pr_tv' => 'Електромонтажник розподільчих пристроїв',
    'nachalnic_viddilu_tv' => 'Начальник відділу',
    'ing_comp_sys_tv' => 'Інженер компютерних систем',
    'ingener_construct_tv' => 'Інженер конструктор',
    'golov_komirnuk_sv' => 'Головний комірник',
    'starsh_komirnuk_sv' => 'Старший комірник',
    'komirnuk_sv' => 'Комірник',
    'director_ad' => 'Директор',
    'zastup_directora_ad' => 'Заступник директора',
    'manager_zbutu_ma' => 'Менеджер із збуту',
    'ing_comp_sys_ma' => 'Інженер компютерних систем',
    'admin_amperok_ma' => 'Адміністратор',
    'paymaster_zalu_ma' => 'Касир залу',
    'bukhhalter_ma' => 'Бухгалтер',
    'vodiy_tra' => 'Водій',
    'dispetcher_tra' => 'Диспетчер',
    'Ingener_praci_tra' => 'Інженер з охорони праці',
    'mekhanik_tra' => 'Механік',
    'ekspeditor_tra' => 'Експедитор',
    'medsestra_tra' => 'Медсестра',
    'logist_bukh' => 'Логіст',
    'bukhhalter_bukh' => 'Бухгалтер',
    'programist_bukh' => 'Програміст',
    'ing_comp_sys_bukh' => 'Інженер компютерних систем',
    'economist_bukh' => 'Економіст',
    'golov_bukhhalter_bukh' => 'Головний бухгалтер',
    'manager_zbutu_int' => 'Менеджер із збуту',
    'mont_radioel_pr_serv' => 'Монтажник радіоелектронних апаратів та приладів',
    'nachalnic_viddilu_serv' => 'Начальник відділу',

    'director_el' => 'Директор',
    'golov_bukhhalter_el' => 'Головний бухгалтер',
    'bukhhalter_el' => 'Бухгалтер',
    'manager_postachaniia_el' => 'Менеджер з постачання',
    'economist_el' => 'Економіст',
    'ingener_el' => 'Інженер',
    'manager_zbutu_el' => 'Менеджер із збуту',
    'office_admin_el' => 'Офіс адміністратор',
    'ekspeditor_el' => 'Експедитор',
    'ing_comp_sys_el' => 'Інженер компютерних систем',
    'komirnuk_el' => 'Комірник',
    'starsh_komirnuk_el' => 'Старший комірник',
    'manager_logist_el' => 'Менеджер з логістики'
];

$capabilities = [
    'read' => false,
    'delete_posts' => false,
    'edit_posts' => false,
    'delete_published_posts' => false,
    'edit_published_posts' => false,
    'publish_posts' => false,
    'upload_files' => false,
    'delete_others_pages' => false,
    'delete_others_posts' => false,
    'delete_pages' => false,
    'delete_private_pages' => false,
    'delete_private_posts' => false,
    'delete_published_pages' => false,
    'edit_others_pages' => false,
    'edit_others_posts' => false,
    'edit_pages' => false,
    'edit_private_pages' => false,
    'edit_private_posts' => false,
    'edit_published_pages' => false,
    'manage_categories' => false,
    'manage_links' => false,
    'moderate_comments' => false,
    'publish_pages' => false,
    'read_private_pages' => false,
    'read_private_posts' => false,
    'unfiltered_html' => false,
    'activate_plugins' => false,
    'create_users' => false,
    'deactivate_plugins' => false,
    'delete_plugins' => false,
    'delete_themes' => false,
    'delete_users' => false,
    'edit_dashboard' => false,
    'edit_files' => false,
    'edit_plugins' => false,
    'edit_theme_options' => false,
    'edit_themes' => false,
    'edit_users' => false,
    'export' => false,
    'import' => false,
    'install_languages' => false,
    'install_plugins' => false,
    'install_themes' => false,
    'list_users' => false,
    'manage_options' => false,
    'promote_users' => false,
    'remove_users' => false,
    'switch_themes' => false,
    'update_core' => false,
    'update_languages' => false,
    'update_plugins' => false,
    'update_themes' => false,
    'unfiltered_upload' => false,
    'manage_network_options' => false,
    'manage_network_plugins' => false,
    'manage_network_themes' => false,
    'manage_network_users' => false,
    'manage_network' => false,
    'manage_sites' => false,
    'setup_network' => false,
    'upgrade_network' => false
];

foreach ($roles as $role_key => $role_name) {
    add_role($role_key, __($role_name), $capabilities);
}